### PR TITLE
fix Composer's semver handling

### PR DESCRIPTION
**Pull request by szepeviktor**
@drupol Composer handles the caret sign in a "special" (incorrect) way.
https://semver.madewithlove.com/?package=php&constraint=%5E8.1

### CODE REVIEW

**Comment by drupol** [comment]
Wow I wasn't expecting comments on this project so fast ! Thank you, TIL !

**Comment by szepeviktor** [comment]
Very glad to contribute.

**Comment by drupol** [comment]
By the way, has this problem be notified to the Composer maintainers guys?

**Comment by szepeviktor** [comment]
I don't have hard enough balls to talk to them about problems.
https://getcomposer.org/doc/articles/versions.md#caret-version-range-

**Comment by drupol** [comment]
OK I will try at some point :)

**Comment by drupol** [comment]
@szepeviktor I'm back on this, what's the issue with the link https://semver.madewithlove.com/?package=php&constraint=%5E8.1 I don't get it, it seems good to me.

**Comment by szepeviktor** [comment]
> what's the issue with the link https://semver.madewithlove.com/?package=php&constraint=%5E8.1

Before this PR it was `^8.0 || ^8.1 || ^8.2` which suggests

`^8.0` means 8.0 <= version < 8.1 etc.
but actually meant 8.0 <= version < 9.0 etc.

**Comment by Seldaek** [comment]
I have no idea what you mean @szepeviktor - Composer's `^` behaves exactly as npm's.

image

See also https://semver.npmjs.com/#syntax-examples

Where we differ is with `~`. Whereas Composer allows you to use `~1.2` to mean `>=1.2 <2`, and `~1.2.0` to mean `>=1.2.0 <1.3`, whereas npm treats both as `>=1.2.0 <1.3`.

Anyway more than balls you need words to explain what is in your opinion that we do wrong.

**Pull request merged**
